language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'

services:
  - mysql

before_install:
- rvm use 2.2 --install --binary --fuzzy
- ruby --version
- mysql -e 'CREATE DATABASE development;'
- nvm install 4.4.7
- npm install -g npm@2.15.8
- npm install -g mocha
- cd client
- npm install
- cd ../tests
- bundle install
- gem install bacon
- cd ../server
- composer install
- nohup bash -c "php -S localhost:8080 2>&1 &" && sleep 1; cat nohup.out
- cd ..

script:
- cd client
- npm test
- cd ../server
- ./run-tests.sh
- cd ../tests
- bacon init.rb
